### PR TITLE
[NO  MRG] MNT: Re-rendered with conda-smithy 3.0.0.rc2 and pinning 2018.03.03

### PR DESCRIPTION
**Pull request by isuruf**
Check conda-smithy=3.0.0

### CODE REVIEW

**Comment by jakirkham** [comment]
Intriguing @isuruf! Thanks for putting this together. So is this based on some development work for `conda-smithy` somewhere?

**Comment by isuruf** [comment]
> So is this based on some development work for conda-smithy somewhere?

No. Just hand editing. As a start I'd like to get https://github.com/conda-forge/conda-smithy/pull/710 in and then work on it after 3.0.0. Also there's a PR at https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/7 too

**Comment by jakirkham** [comment]
Is this still needed given PR ( https://github.com/conda-forge/occt-feedstock/pull/23 ) went in?

**Comment by looooo** [comment]
Right. Everything should be included already.

**Pull request closed without merging**
