### PR TITLE
add pcc64le support

### LINKED ISSUE #60: ppc64le package
Can you please create a ppc64le version of this package?

### PR DESCRIPTION
**Pull request by matthiasdiener**
Needs https://github.com/conda-forge/vtk-feedstock/pull/165

Fixes #60.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
@conda-forge-admin, please restart ci

**Comment by matthiasdiener** [comment]
@conda-forge-admin, please restart ci

**Comment by matthiasdiener** [comment]
Ready for review @looooo

**Comment by isuruf** [comment]
Should be closed in favour of https://github.com/conda-forge/occt-feedstock/pull/64 which does native builds compared to cross builds here.

**Pull request closed without merging**
