### PR TITLE
Patch boolean intersection

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
Thanks @basnijholt 
If this build is not binary compatible we have to take care about naming. Best to try locally first.

**Comment by looooo** [comment]
Building this branch locally seems to work with latest FreeCAD and netgen (tested on linux). So I guess it's ok to apply this PR. But I think it's best to wait for a feedback from the experts: https://forum.freecadweb.org/viewtopic.php?f=10&t=36828

**Comment by basnijholt** [comment]
Thanks for the help 👍 

It seems like the experts [say it is OK](https://forum.freecadweb.org/viewtopic.php?f=10&t=36828).

**Comment by looooo** [comment]
Great!

**Pull request merged**
