### PR TITLE
MNT: Re-rendered with conda-build 3.19.2, conda-smithy 3.7.5, and con…

### PR DESCRIPTION
**Pull request by looooo**
After adding vtk-dependency we forgot to rerender...
once this PR is merged we need to set all occt-builds dependent on vtk to broken 

…da-forge-pinning 2020.07.29.10.14.20

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge/core I need to split the package into two packages:

- occt
- occt-vtk

 occt-vtk depends on vtk and is basically one library (3 files): `lib/libTKIVtk.so lib/libTKIVtk.so.7 lib/libTKIVtk.so.7.4.0`

What's the easiest way to do that?

**Comment by beckermr** [comment]
Use outputs. See the conda build documentation.

**Comment by looooo** [comment]
@adam-urbanczyk is it ok if we merge this one before jumping to vtk9? I would like to have the pinning fixed for occt with vtk8.2.

**Comment by adam-urbanczyk** [comment]
Sure, no problem @looooo

**Pull request closed without merging**
