### PR TITLE
7.5 beta [WIP]

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@adam-urbanczyk it's best to make the PR against the rc-branch. At least this is suggested by [cfep05](https://github.com/conda-forge/cfep/blob/master/cfep-05.md).

> To create a dev or rc package a PR can be issued into the dev or rc branch of the feedstock. This branch must change the recipe/conda_build_config.yaml to point to the <package_name>_dev or <package_name>_rc label.

**Comment by adam-urbanczyk** [comment]
OK, will do that.

**Comment by looooo** [comment]
any idea?
```
LINK: command "C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtk\IVtk_Interface.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtk\IVtk_IShape.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtk\IVtk_IShapeData.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtk\IVtk_IShapeMesher.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtk\IVtk_IShapePickerAlgo.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtk\IVtk_IView.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkOCC\IVtkOCC_SelectableObject.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkOCC\IVtkOCC_Shape.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkOCC\IVtkOCC_ShapeMesher.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkOCC\IVtkOCC_ShapePickerAlgo.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkOCC\IVtkOCC_ViewerSelector.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkVTK\IVtkVTK_ShapeData.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkVTK\IVtkVTK_View.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkTools\IVtkTools.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkTools\IVtkTools_DisplayModeFilter.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkTools\IVtkTools_ShapeDataSource.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkTools\IVtkTools_ShapeObject.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkTools\IVtkTools_ShapePicker.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\IVtkTools\IVtkTools_SubPolyDataFilter.cxx.obj src\TKIVtk\CMakeFiles\TKIVtk.dir\__\__\resources\TKIVtk.rc.res /out:win64\vc14\bin\TKIVtk.dll /implib:win64\vc14\lib\TKIVtk.lib /pdb:win64\vc14\bin\TKIVtk.pdb /dll /version:7.5 /machine:x64 /INCREMENTAL:NO -LIBPATH:%PREFIX%\Library\lib win64\vc14\lib\TKV3d.lib %PREFIX%\Library\lib\vtkRenderingFreeType-9.0.lib %PREFIX%\Library\lib\vtkInteractionStyle-9.0.lib %PREFIX%\Library\lib\vtkRenderingGL2PSOpenGL2-9.0.lib win64\vc14\lib\TKMesh.lib win64\vc14\lib\TKService.lib %PREFIX%\Library\lib\FreeImage.lib winmm.lib win64\vc14\lib\TKShHealing.lib opengl32.lib %PREFIX%\Library\lib\freetype.lib win64\vc14\lib\TKHLR.lib win64\vc14\lib\TKTopAlgo.lib win64\vc14\lib\TKGeomAlgo.lib win64\vc14\lib\TKBRep.lib win64\vc14\lib\TKGeomBase.lib win64\vc14\lib\TKG3d.lib win64\vc14\lib\TKG2d.lib win64\vc14\lib\TKMath.lib win64\vc14\lib\TKernel.lib advapi32.lib gdi32.lib user32.lib wsock32.lib psapi.lib %PREFIX%\Library\lib\tbb.lib %PREFIX%\Library\lib\tbbmalloc.lib %PREFIX%\Library\lib\freetype.lib %PREFIX%\Library\lib\vtkRenderingOpenGL2-9.0.lib %PREFIX%\Library\lib\vtkRenderingUI-9.0.lib %PREFIX%\Library\lib\vtkRenderingCore-9.0.lib %PREFIX%\Library\lib\vtkFiltersGeneral-9.0.lib %PREFIX%\Library\lib\vtkFiltersCore-9.0.lib %PREFIX%\Library\lib\vtkCommonExecutionModel-9.0.lib %PREFIX%\Library\bin\glew32.dll %PREFIX%\Library\lib\vtkCommonDataModel-9.0.lib %PREFIX%\Library\lib\vtkCommonMisc-9.0.lib %PREFIX%\Library\lib\vtkCommonTransforms-9.0.lib %PREFIX%\Library\lib\vtkCommonMath-9.0.lib %PREFIX%\Library\lib\vtkCommonCore-9.0.lib %PREFIX%\Library\lib\vtksys-9.0.lib ws2_32.lib dbghelp.lib psapi.lib %PREFIX%\Library\bin\tbb.dll kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:win64\vc14\bin\TKIVtk.dll.manifest" failed (exit code 1107) with the following output:
IVtk_Interface.cxx.obj : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
%PREFIX%\Library\bin\glew32.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x2D8

```

https://stackoverflow.com/questions/35916703/error1-error-lnk1107-invalid-or-corrupt-file-cannot-read-at-0x2b0

**Comment by adam-urbanczyk** [comment]
Somehow cmake wants to link against the dll and it should link against lib. I modified the generated ninja file to link against glew32.lib and the thing now compiles. Investigating now how to patch CMakeLists to solve this.

**Comment by adam-urbanczyk** [comment]
If it passes now (it does work locally) I'll clean up and reopen in the correct branch.

**Pull request closed without merging**
