### PR TITLE
VTK support

### LINKED ISSUE #34: VTK modules
I'd like to use the VTK integration modules of OCCT. Is there any reason why they are disabled? I think it comes down to specifying
```
-DUSE_VTK:BOOL=ON
```
and adding VTK as a dep. It is already available on conda-forge.

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Will resolve #34

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
Any clue what is with the missing `libXext` rule @looooo ? If I remove it from `build.ninja` by hand all compiles fine on Linux. I tried to look at he CMake files of OCCT but they look really messy.

It'd be great if you could look at OSX, I have no access to such machine for debugging.

**Comment by looooo** [comment]
linux: 
```
ninja: error: '/usr/lib64/libXext.so', needed by 'lin64/gcc/lib/libTKIVtk.so.7.4.0', missing and no known rule to make it
Traceback (most recent call last):
```

I guess this is wrong. It shouldn't directly link to /usr/lib64 libraries.

win:

```
fatal error C1085: Cannot write compiler generated file: '%SRC_DIR%\build\src\TKVRML\CMakeFiles\TKVRML.dir\__\VrmlData\VrmlData_IndexedLineSet.cxx.obj': No space left on device
```
osx: 
```
CMake Error in src/TKIVtk/CMakeLists.txt:
  No known features for CXX compiler

  "Clang"

  version 9.0.1.
```

I have seen this somewhere else, but can't remember how we solved that... something about cmake policies?

**Comment by adam-urbanczyk** [comment]
Regarding windows, it seems to be simply running out of disk space. Do you know how to change the available disk quota?

**Comment by looooo** [comment]
sry, I don't know if there is a possibility to increase allowed disc space. Bigger packages like qt are compiled locally for windows.

**Comment by adam-urbanczyk** [comment]
Note to self: this might be interesting https://stackoverflow.com/questions/47269979/using-the-ninja-build-system-can-i-clean-intermediate-build-products

**Comment by adam-urbanczyk** [comment]
Linux and OSX seem to work, do you have any guidance on handling the win build @looooo ?

**Comment by adam-urbanczyk** [comment]
I'm going crazy with this. Local build takes 1.2G, CI build takes 10G. I checked on one specific file (`V3d.cxx.obj`) and it takes locally 125K and 3.5M on the build agent. Both generated using the conda recipe in question (and conda build). 

I asked on the conda-forge gitter , are there any alternative support channels that I should use @looooo ?

**Comment by looooo** [comment]
great. Is this ready? Please increase the build-number in the meta.yml file.

**Comment by adam-urbanczyk** [comment]
Yes, ready for merging @looooo . It was a struggle with the implicit `-GL` flag injected by the compiler activation script from `vs2015_win-64`. Good to know for the future.

Thanks @isuruf for helping to solve this. Would a PR with a doc/FAQ update be welcome? If so, please share the location.

**Comment by looooo** [comment]
@adam-urbanczyk Something on windows went terribly wrong. The package contains not the right files.
https://github.com/conda-forge/cf-mark-broken/pull/34

**Comment by adam-urbanczyk** [comment]
Looking into it @looooo .

**Comment by adam-urbanczyk** [comment]
Actually, it seems to contain all the files but in a weird layout.

**Pull request merged**
