### PR TITLE
add osx_arm64 support

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@isuruf how to distinguish `lgpl2-only` and `lgpl2-or-later`?
Need this for some other recipes too.

**Comment by matthiasdiener** [comment]
@conda-forge-admin rerender

**Comment by matthiasdiener** [comment]
This is ready @looooo @conda-forge/occt

**Comment by isuruf** [comment]
> how to distinguish lgpl2-only and lgpl2-or-later?

If the package doesn't explicitly mention that the lciense is lgpl2-or-later, then go with lgpl2-only.

**Comment by looooo** [comment]
Thanks @matthiasdiener

**Comment by looooo** [comment]
The master branch has travis osx enabled which fails. So we need travis/osx? @matthiasdiener

**Comment by matthiasdiener** [comment]
> The master branch has travis osx enabled which fails. So we need travis/osx? @matthiasdiener

I'm not sure why this is happening, maybe @isuruf knows more.

**Pull request merged**
