### PR TITLE
disable exceptions

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge/core this is failing with this error:
```
Packaging occt
INFO:conda_build.build:Packaging occt
INFO:conda_build.build:Packaging occt-7.5.3-h8294837_4
Packaging occt-7.5.3-h8294837_4
    call_conda_build(action, config)
  File "C:\Miniconda\lib\site-packages\boa\cli\mambabuild.py", line 211, in call_conda_build
    result = api.build(
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 186, in build
    return build_tree(
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2371, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1664, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1510, in post_process_files
    post_build(m, new_files, build_python=python)
  File "C:\Miniconda\lib\site-packages\conda_build\post.py", line 1318, in post_build
    check_overlinking(m, files, host_prefix)
  File "C:\Miniconda\lib\site-packages\conda_build\post.py", line 1224, in check_overlinking
    return check_overlinking_impl(m.get_value('package/name'),
  File "C:\Miniconda\lib\site-packages\conda_build\post.py", line 1048, in check_overlinking_impl
    packages = dists_from_names(requirements_run, run_prefix)
  File "C:\Miniconda\lib\site-packages\conda_build\post.py", line 639, in dists_from_names
    pkgs = linked_data_no_multichannels(prefix)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 2084, in linked_data_no_multichannels
    from conda.common.compat import itervalues
ImportError: cannot import name 'itervalues' from 'conda.common.compat' (C:\Miniconda\lib\site-packages\conda\common\compat.py)

```

**Comment by hmaarrfk** [comment]
I think this is related to https://github.com/conda-forge/conda-forge.github.io/issues/1762#issuecomment-1139603444

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by looooo** [comment]
thanks

**Pull request merged**
