### PR TITLE
VTK9 fix [WIP]

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@conda-forge-admin, please rerender

**Comment by adam-urbanczyk** [comment]
@looooo I think this is ready for merging, how do you want to proceed with the split?

**Comment by looooo** [comment]
@adam-urbanczyk great work! I am not sure if splitting makes a lot of sense. My idea was to build occt with vtk disabled and afterwards with vtk enabled. But this way there are some cmake-files that are different and overlapping. Also I am not sure if running the cmake twice is working with outputs...

So I will do a rerendering today to get the pinning with vtk8.2 right. Once that is done we merge this branch. Working on the split might need some more time, and maybe it's better to do this at a later point.

**Comment by looooo** [comment]
btw.: you need to add the migration file to `.ci_support/migrations` https://github.com/conda-forge/occt-feedstock/blob/d37f5380cc1ccc4e4869dddf372da4bdf235b429/.ci_support/migrations/vtk901.yaml to get vtk9 pinned after rerendering.

**Comment by adam-urbanczyk** [comment]
@conda-forge-admin, please rerender

**Comment by adam-urbanczyk** [comment]
I think it is done, please let me know @looooo if additional actions are required.

**Comment by adam-urbanczyk** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
