### PR TITLE
Suggested split of occt into packages with and without VTK

### LINKED ISSUE #93: Create multiple OCCT packages with different number of dependencies (with/without VTK etc.)
Hey,

I was wondering if it could make sense to create multiple OCCT packages with varying number of dependencies? The motivation would be to make it possible to reduce the number of dependencies based on what functionality in OCCT you need?

For example, to start, perhaps compile an additional occt version without VTK (which seem to be adding more dependencies than occt itself)?

If this is something that others might find useful, I can start on making a PR with attempting to add a multi-build setup in the meta.yaml. There we can discuss further, such as potential name-conventions etc...

Any thoughts on this? @looooo @adam-urbanczyk

### PR DESCRIPTION
**Pull request by Krande**
Hey,

continuing the discussion from https://github.com/conda-forge/occt-feedstock/issues/93 here's a proposal for splitting occt into two packages `occt-vtk` & `occt-core` which respectively are with/without VTK. The motivation behind the proposal is to reduce the number of required dependencies for downstream packages that does not need VTK.

FYI I have tested the occt-core dependency on the following packages that seems to be unaffected by the removal of VTK.

* [python-gmsh](https://github.com/conda-forge/gmsh-feedstock)
* [IfcOpenShell](https://github.com/conda-forge/ifcopenshell-feedstock)
* [pythonocc-core](https://github.com/conda-forge/pythonocc-core-feedstock)

(For those who wants to test `occt-core` with python-gmsh, ifcopenshell and pythonocc-core I have published them on my Anaconda repo: https://anaconda.org/krande/repo )

I am happy to discuss naming convention, build procedure and also testing of other downstream packages that would be affected by this proposal.

One alternative naming convention would be to change the proposed name `occt-vtk` to just `occt`. That could perhaps be less disruptive, leaving it up to downstream packages to move to the lighter `occt-core` package. However, I am unsure how I would solve that using conditionals and build variants in the conda_build_config.yaml. But it certainly should be doable.

Let me know what your thoughts are?

* closes #93 

Best Regards
Kristoffer

### CODE REVIEW

**Comment by whophil** [comment]
@Krande I could be wrong, but I believe this type of thing is more commonly done using the build string to denote different variants, rather than the package name.

For example, see the VTK feedstock @ https://github.com/conda-forge/vtk-feedstock/blob/809902f63a8c8c81f05c4bf9ccbf1be1cde171ba/recipe/meta.yaml#L30

**Comment by Krande** [comment]
Hey @whophil! Thanks for the suggestion :) This is uncharted waters for me, so I am happy to explore more suitable options! 

Regarding the `vtk` package build string, how would you typically do conda install vtk + qt or osmesa? Do you have to use the entire build string or is there a shorter simpler form?

**Comment by whophil** [comment]
> Regarding the `vtk` package build string, how would you typically do conda install vtk + qt or osmesa? Do you have to use the entire build string or is there a shorter simpler form?

The format is
```
conda install <package_name>=<version>=<build_string>
```

Asterisk wildcards can also be used, if encapsulated in single quotes, e.g.,

```
conda install 'vtk=*=qt*'
```

or 

```
conda install 'vtk=*=no_osmesa*'
```

**Comment by Krande** [comment]
okay, that makes sense. 

Any idea what the default option would be and how that would be set? Ie. when I did `mamba install vtk` just now it tries to install the `qt` variant -> `+ vtk                               9.2.6  qt_py311hd10cacf_200  conda-forge/win-64       31MB`.

**Comment by whophil** [comment]
@Krande the preference for build strings has always been a mystery to me. I just assumed it is not guaranteed.

In the conda-forge knowledge base, they recommend making one variant preferred by giving it a higher build number. See https://conda-forge.org/docs/maintainer/knowledge_base.html#including-a-no-mpi-build

**Comment by Krande** [comment]
@whophil I made a new [commit](https://github.com/conda-forge/occt-feedstock/pull/95/commits/c520998d8539418af9e194407ff9a3c6ccd40cfa) now where I keep the original `occt` name for the unchanged variant (with VTK included). 

That way this PR only introduces 1 extra alternative package `occt-core` (which is probably the least disruptive option). 

Given my little experience with build strings I suggest for now we give the other package a different name to differentiate the variants as opposed to modifying the build string. 


@adam-urbanczyk @looooo Any thoughts on this?

**Comment by Krande** [comment]
After testing build strings for a few days my comfort level with the "build string" concept has increased and I also see the benefits of using build strings compared with creating two separate package :) 

So in https://github.com/conda-forge/occt-feedstock/pull/95/commits/6980df077298e64a4357df01fffbb399702dc0e9 I have implemented a build string based on the suggestion by @whophil.

I have set the `vtk` variant as the highest priority for now (to minimize disruption in any downstream packages that might be dependent on vtk-capabilities in occt).

To specify the `core` variant you will have to do `mamba install occt=*=core*`

To reiterate the benefits of splitting into **core** & **vtk** variants, here's the number of dependencies and estimated installation size for the 2 variants on **windows** (the sizes are approximately the same on linux. Haven't checked OSX, but my guess is that they would be pretty similar):

| occt build variant | nomkl | size [MB] | number of deps |
|--------------------|-------|-----------|----------------|
| vtk                | true  | 299       | 118            |
| occt               | true  | 43        | 31             |
| vtk                | false | 495       | 112            |
| occt               | false | 43        | 31             |

I have packaged the vtk/core variants on my Anaconda `dev` channel (ie. you can do `mamba install -c krande/label/dev occt=*=core*` or `mamba install -c krande/label/dev occt` to test this yourself). 

Note! I include `nomkl` to use `libblas` instead of intel `mkl` to keep the installation size as small as possible. With `mkl` (which is the default today) the ``vtk` variant installation size jumps to 495MB from 299MB. The `core` variant does not rely on `mkl` so mkl/nomkl does not matter on size or number of deps.


@looooo Any chance we might be able to merge this PR?

**Comment by whophil** [comment]
> Note! I include `nomkl` to use `libblas` instead of intel `mkl` to keep the installation size as small as possible. With `mkl` (which is the default today) the `vtk` variant installation size jumps to 495MB from 299MB. The `core` variant does not rely on `mkl` so mkl/nomkl does not matter on size or number of deps.

@Krande I think you were referring to your own personal builds, but all builds on conda-forge CI which require BLAS at compile-time will use the netlib implementation (see https://conda-forge.org/docs/maintainer/knowledge_base.html#blas).

Another topic - I'm wondering if these are the best build strings.

As an alternative - `all` and `novtk`, with `all` being the preferred one.

The reasoning is that the current OCCT build has "all" features enabled, and that should remain the default. A variant named `novtk` makes it absolutely clear that (only) VTK support is disabled in that variant.

**Comment by Krande** [comment]
@whophil Regarding MKL vs BLAS I am sure you are right. I only meant to highlight that for users on Windows any downstream conda package that does not explicitly set BLAS as a dependency (for example `Ifcopenshell`, `pythonocc-core` and gmsh) will automatically pull the MKL package by default.

Good point on the string names. The reasoning behind the proposals of `core` and `vtk` was 

**core**: The core functionality of opencascade
**vtk**: Includes the visualization component (vtk)

Maybe `vtk` and `novtk` would be more appropriate? However, if Opencascade in the future adds features by supporting new 3rd party packages we might have more flexibility with the `core`/`vtk` as opposed to a `vtk`/`novtk` or `all`/`novtk`. What do you think?

Something else that occurred to me is when I look at https://github.com/conda-forge/vtk-feedstock/blob/main/recipe/meta.yaml I see that there are at least 3 build variants of VTK. Are all 3 compatible with the same `occt` package?

And since we already are discussing the different dependencies. Looking at the run requirements, are we sure all of them really are necessary?

    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - rapidjson
    - vtk  # [variant=='vtk'] 
    
Sorry for the barrage of questions :)

**Comment by adam-urbanczyk** [comment]
+1 for `all` and `novtk`

**Comment by Krande** [comment]
If the majority vote is for `all` & `novtk` I'll support it :) 

@looooo Does this sound OK to you?

**Comment by Krande** [comment]
@whophil Should we perhaps ask the conda-forge admins to perhaps add the two of us as maintainers so that we can offload @looooo when he is unable to review?

**Comment by whophil** [comment]
Hi @Krande - I'd prefer not to be listed as a maintainer of this feedstock, as I am only a third-hand consumer of it via the [OCP](https://github.com/CadQuery/OCP) project (@adam-urbanczyk).

Probably the largest direct consumer of this feedstock is the [freecad-feedstock](https://github.com/conda-forge/freecad-feedstock). I would suggest that somebody from that project could volunteer to maintain this feedstock, but it looks like @looooo is the only maintainer of that feedstock as well...

**Comment by Krande** [comment]
Fair enough @whophil :) I will try to ask the conda forge admins to give me access.

**Comment by looooo** [comment]
It said that it's not possible by reading but merging is ok. Does this change anything for occt-dependent packages?

Also I don't see the vtk-independent packages being built. Is there still something missing?

**Comment by Krande** [comment]
@looooo thanks for taking the time to check (also it is good to hear from you :) 

It shouldn't really interfere with any downstream dependencies given that we've set a higher build number for the `all` variant
(which is the equivalent of `occt` today). 

I've checked the azure pipelines logs and things seem to look OK on my end. Does it look different on your end?

image

*From the Azure Pipeline logs*

[LINUX]

[start of `all` build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=693513&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=38)

    BUILD START: ['occt-7.7.1-all_hf45a015_200.conda']
    Reloading output folder: /home/conda/feedstock_root/build_artifacts

[start of `novtk` build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=693513&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=16018)

    BUILD START: ['occt-7.7.1-novtk_hc4316ec_100.conda']
    Reloading output folder: /home/conda/feedstock_root/build_artifacts


[built packages](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=693513&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=31423)

	{
	  "occt-7.7.1-all_hf45a015_2": {
		"recipe": {
		  "channel_targets": "conda-forge main",
		  "cxx_compiler": "gxx",
		  "cxx_compiler_version": "11",
		  "fontconfig": "2",
		  "freetype": "2",
		  "target_platform": "linux-64",
		  "variant": "all",
		  "vtk": "9.2.5"
		}
	  },
	  "occt-7.7.1-novtk_hc4316ec_1": {
		"recipe": {
		  "channel_targets": "conda-forge main",
		  "cxx_compiler": "gxx",
		  "cxx_compiler_version": "11",
		  "fontconfig": "2",
		  "freetype": "2",
		  "target_platform": "linux-64",
		  "variant": "novtk"
		}
	  }
	}

[WINDOWS]

[start of `all` build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=693513&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=32)

    BUILD START: ['occt-7.7.1-all_h13609b4_200.conda']
    Reloading output folder: C:\bld

[start of `novtk` build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=693513&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=16921)

    BUILD START: ['occt-7.7.1-novtk_hdfb195f_100.conda']
    Reloading output folder: C:\bld
    
[built packages](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=693513&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=33165)

	{
	  "occt-7.7.1-all_h13609b4_2": {
		"recipe": {
		  "channel_targets": "conda-forge main",
		  "cxx_compiler": "vs2019",
		  "fontconfig": "2",
		  "freetype": "2",
		  "target_platform": "win-64",
		  "variant": "all",
		  "vtk": "9.2.5"
		}
	  },
	  "occt-7.7.1-novtk_hdfb195f_1": {
		"recipe": {
		  "channel_targets": "conda-forge main",
		  "cxx_compiler": "vs2019",
		  "fontconfig": "2",
		  "freetype": "2",
		  "target_platform": "win-64",
		  "variant": "novtk"
		}
	  }
	}

**Comment by looooo** [comment]
ah, nice. didn'T realize that this runs inside one action-process. Ok, then I think this is ready to merged.

**Comment by Krande** [comment]
@looooo should we try to merge this? :)

**Comment by adrianinsaval** [comment]
looks like new packages where not uploaded:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=700041&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=6494c7a6-a019-59a3-6f3d-9bab8ca96717&t=47f1ac7e-d0be-5d8d-6da0-bd921ed9abfb
> ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
> copy results:
> {}
> Failed to upload due to copy from staging to production channel failed. Trying again in 153.93679428100586 seconds
> 

maybe just need to retrigger the CI?

**Comment by thomashampson** [comment]
Do you know the correct syntax for specifying the `novtk` build variant within a conda-build recipe? We have `occt` as a host and run dependency and I'm not sure if putting `'=*=novtk*'` in both sections will override your run_export for ABI compatiblity.

**Comment by Krande** [comment]
@thomashampson That's a good question. I think that is the appropriate way of handling occt pinning as it stands today.

It has been my understanding (and I might be wrong) that the "run_export" pinning on the occt packages will automatically pin the runtime version of occt used by any downstream packages in their host requirement. So I would assume that your solution should work (the version is pinned, but the variant is not, so you rightly include a variant pinning in your run requirement).

Maybe an improvement of the current occt package would be to mimic the HDF5 package behaviour wrt. mpi. (see https://github.com/conda-forge/hdf5-feedstock/blob/main/recipe/meta.yaml#L58)

That way the variant of the run_export will be included in the pinning. If my interpretation is correct, this would remove any need for specifying occt in your run requirements (it should automatically pin both version and variant as a runtime requirement).

**Pull request merged**
