### PR TITLE
feat: update to 7.7.0

### PR DESCRIPTION
**Pull request by Michsior14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Michsior14** [comment]
@conda-forge-admin, please rerende

**Comment by Michsior14** [comment]
@conda-forge-admin, please rerender

**Comment by Michsior14** [comment]
@looooo Could you please have a look on `blobfish.patch` (failing `ElSLib::ConeDN` patch)? I have no knowledge of changes done over there.

**Comment by looooo** [comment]
> @looooo Could you please have a look on `blobfish.patch` (failing `ElSLib::ConeDN` patch)? I have no knowledge of changes done over there.

I guess we have to update these patches. https://forum.freecadweb.org/viewtopic.php?f=8&t=72244

**Comment by Michsior14** [comment]
> > @looooo Could you please have a look on `blobfish.patch` (failing `ElSLib::ConeDN` patch)? I have no knowledge of changes done over there.
> 
> I guess we have to update these patches. https://forum.freecadweb.org/viewtopic.php?f=8&t=72244

Thanks for the hint, I've just updated them and CI looks promising ;)

**Comment by Michsior14** [comment]
@looooo Please review once you have time

**Pull request merged**
