### PR TITLE
Build 7.6.0

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@conda-forge-admin, please rerender

**Comment by adam-urbanczyk** [comment]
@looooo are the travis and aarch64 timeouts to be expected? There is nothing I can do about them.

**Comment by realthunder** [comment]
`fix-step-import` and `error-checking` no longer apply to 7.6. Not sure about the others.

**Comment by looooo** [comment]
@conda-forge-admin, please restart ci

**Comment by looooo** [comment]
We can work on aarch64 also later on if it also fails after the merge. Not sure if anyone uses the aarch64 builds. I guess it's not high priority.

**Pull request merged**
