### PR TITLE
add run_exports

### PR DESCRIPTION
**Pull request by matthiasdiener**
See https://github.com/conda-forge/occt-feedstock/issues/97, https://github.com/conda-forge/gmsh-feedstock/pull/72 for context.

cc @isuruf @inducer

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
A gentle ping for review @conda-forge/occt  @isuruf

**Comment by whophil** [comment]
Does this mean that projects which list `occt` as a `host` dep will be automatically given a run dep of `occt` with a version strictness of `x.x.x`? If so, it would be great if we could get this merged. Thanks!

**Comment by matthiasdiener** [comment]
> Does this mean that projects which list `occt` as a `host` dep will be automatically given a run dep of `occt` with a version strictness of `x.x.x`?

Yes, that is my understanding as well.

**Comment by whophil** [comment]
@looooo could we get this merged in?

Also a more general question, maybe for @isuruf - how does this interact with this `pin_run_as_build` in global pinning?
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L202-L203

**Pull request merged**
